version: 2.1.0.{build}
branches:
  only:
  - master
  - dev
  - ci
configuration: Release
clone_folder: c:\projects\enjoycqrs
clone_depth: 1
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COVERALLS_REPO_TOKEN:
    secure: kHP+PNmg4mKBU2zHqiMfKsj/j2tAjx/XF4/GC7c9sQkUnn2K6VisA91ad9jH9qod
skip_commits:
  message: /updated readme.*/
build_script:
- ps: .\build.ps1 -Target AppVeyor
test: off
artifacts:
  - path: artifacts\test-results\*.*
    name: test-results
  - path: artifacts\nugets\*.*
    name: nugets
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: NAbtRfAbJ7QcwtGR75wAcofcV+ipa6tKWGP798krZRjOYParVolf71xX5JBy+rUR
  on:
    branch: master
- provider: NuGet
  skip_symbols: true
  server: https://www.myget.org/F/enjoy/api/v2/package
  api_key:
    secure: zPU3TMfMcbGiOTRpcKdNjztuCMOtjdBB0ReA9tkMCs9XKejC9NKMVvEGvz7HFmEP
  on:
    branch: 
    - dev
    - ci