version: 1.0.{build}
branches:
  only:
  - dev
configuration: Debug
platform: Any CPU
clone_depth: 1
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- ps: nuget pack EnjoyCQRS.nuspec -Version $env:appveyor_build_version
artifacts:
- path: *.nupkg
  name: nuget-pkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/enjoy/api/v2/package
  api_key:
    secure: zPU3TMfMcbGiOTRpcKdNjztuCMOtjdBB0ReA9tkMCs9XKejC9NKMVvEGvz7HFmEP
  artifact: nuget-pkg
  on:
    branch: dev